name: btest2-env-timeout

on:
  push:
    branches:
      - 'out-s3-unsigned-payload-v5.1.1'
  workflow_dispatch:

env:
  IMAGE: registry.graphicsoft.com.cn/library/fluent/fluent-bit:5.1.1-out_s3_patch

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: docker version
        run: docker version
      - name: use env IMAGE
        run: echo "IMAGE=${IMAGE}"
