name: docker-capability-test

on:
  push:
    branches:
      - 'out-s3-unsigned-payload-v5.1.1'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: docker version
        run: docker version
      - name: hello
        run: echo "workflow ran with a job"
